[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
bevy = { version = "0.12.1" }
bincode = "1.3.3"
bevy_egui = "0.24.0"
bevy_matchbox = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
