[workspace]
resolver = "2"
members = [
  "client", "server", "shared",
]

[profile.wasm-dev]
inherits = "dev"

[profile.wasm-dev.package."*"]
opt-level = "z"
codegen-units = 1

[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = "fat"
codegen-units = 1
